# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ze1ym5yavivTpNe_rueIIhD_29mACkWU
"""

import pandas as pd

import pandas as pd
import numpy as np

# 1. Load the dataset
df = pd.read_csv('retail_store_sales.csv')

# 2. Fix Missing "Item" names
# Since we don't know the exact names, we fill them with 'Unknown_Item'
df['Item'] = df['Item'].fillna('Unknown_Item')

# 3. Handle Missing Numerical Values (Price and Quantity)
# We fill missing prices and quantities with the 'Median' value so they don't skew the data
df['Price Per Unit'] = df['Price Per Unit'].fillna(df['Price Per Unit'].median())
df['Quantity'] = df['Quantity'].fillna(df['Quantity'].median())

# 4. Feature Engineering: Re-calculate Total Spent
# Some 'Total Spent' values are missing. We calculate them: Price * Quantity
df['Total Spent'] = df['Total Spent'].fillna(df['Price Per Unit'] * df['Quantity'])

# 5. Standardize Date Format
# Convert the 'Transaction Date' column from a string to a proper Python Date object
df['Transaction Date'] = pd.to_datetime(df['Transaction Date'])

# 6. Handle "Discount Applied"
# If it's missing, we assume no discount was given (False)
df['Discount Applied'] = df['Discount Applied'].fillna(False)

# 7. Feature Engineering: Extracting Time Data
# We create a new 'Month' column to help with future analysis
df['Transaction_Month'] = df['Transaction Date'].dt.month_name()

# 8. Export the clean data
df.to_csv('cleaned_retail_store_sales.csv', index=False)
print("Data cleaning complete! File 'cleaned_retail_store_sales.csv' is ready.")